In [9]:
import pyodbc
import pandas as pd
import csv

In [10]:
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=cmdaserver.database.windows.net;"
    "DATABASE=CMDACopy;"
    "UID=CMDAUser;"
    "PWD=FarmiAnalysis123!;"
)
cursor = conn.cursor()

In [11]:
cursor.execute("""SELECT temp_farm_crop_baseline.*, t_user.company_id FROM temp_farm_crop_baseline 
               inner join t_farm on temp_farm_crop_baseline.farm_id = t_farm.farm_id
               inner join t_user on t_farm.user_id = t_user.user_id
               """)

column_names = [description[0] for description in cursor.description]

# Print the headers
print(','.join(column_names))

# Fetch and print each row
for row in cursor:
    print(','.join(map(str, row)))

farm_id,crop_id,crop_area,land_preparation_cost,planting_material_cost,labour_cost,fertilizer_cost,pest_disease_cost,other_cost,total_cost,total_yield,yield_quality,total_revenue,net_profit,baseline,company_id
126,354,0.50,4000.00,2000.00,2000.00,2500.00,2500.00,0.00,13000.00,1300.00,90.00,26000.00,13000.00,Y,1000
126,354,0.50,2500.00,2000.00,2500.00,3000.00,2500.00,0.00,12500.00,1000.00,90.00,30000.00,17500.00,N,1000
444,354,0.50,4000.00,4000.00,10000.00,9000.00,8000.00,4000.00,39000.00,4000.00,90.00,160000.00,121000.00,Y,1000
444,354,0.50,6000.00,5000.00,7000.00,4000.00,4000.00,0.00,26000.00,2000.00,85.00,70000.00,44000.00,N,1000
529,229,0.25,3000.00,4800.00,5000.00,3800.00,3600.00,0.00,20200.00,3500.00,80.00,48000.00,27800.00,Y,1000
529,229,0.25,6000.00,1500.00,1500.00,10000.00,5000.00,0.00,24000.00,18000.00,90.00,288000.00,264000.00,N,1000
543,358,1.00,3500.00,2800.00,4500.00,3800.00,2300.00,0.00,16900.00,1750.00,85.00,125000.00,108100.00,Y,1000
543,358,1.00,5000.00,10000.00,8000.00,5000.00,4000.00,0.00,32000.00,30000.00,85.00,540000.00,508000.00,N,1000
573,354,1.00,4000.00,4500.00,6000.00,4000.00,2500.00,0.00,21000.00,5800.00,95.00,65000.00,44000.00,Y,1000
573,354,1.00,6000.00,5000.00,4000.00,6000.00,3000.00,0.00,24000.00,7500.00,85.00,187500.00,163500.00,N,1000
628,354,0.50,4000.00,2000.00,2000.00,3000.00,1500.00,0.00,12500.00,1500.00,90.00,30000.00,17500.00,Y,1000
628,354,0.50,4000.00,3000.00,4000.00,3000.00,2500.00,0.00,16500.00,1500.00,90.00,60000.00,43500.00,N,1000
633,358,0.50,7000.00,2000.00,3000.00,4000.00,4000.00,0.00,20000.00,4500.00,85.00,85500.00,65500.00,Y,1000
633,358,0.50,6000.00,3500.00,3500.00,4500.00,3000.00,0.00,20500.00,9000.00,90.00,225000.00,204500.00,N,1000
634,359,0.50,3000.00,4000.00,3000.00,4000.00,4000.00,0.00,18000.00,1000.00,80.00,10000.00,-8000.00,Y,1000
634,359,0.50,4000.00,3000.00,3000.00,3000.00,2500.00,0.00,15500.00,1400.00,90.00,70000.00,54500.00,N,1000
635,355,0.50,3000.00,2500.00,3000.00,4000.00,4000.00,0.00,16500.00,3000.00,95.00,90000.00,73500.00,Y,1000
635,355,0.50,4000.00,2000.00,4500.00,3000.00,3000.00,0.00,16500.00,9000.00,85.00,360000.00,343500.00,N,1000
636,358,0.50,4000.00,2000.00,3000.00,3000.00,2500.00,0.00,14500.00,4000.00,95.00,60000.00,45500.00,Y,1000
636,358,0.50,3000.00,3000.00,2500.00,3000.00,2500.00,0.00,14000.00,5000.00,90.00,200000.00,186000.00,N,1000
637,352,0.50,3000.00,3000.00,2000.00,3000.00,3000.00,0.00,14000.00,6000.00,80.00,130000.00,116000.00,Y,1000
637,352,0.50,3000.00,3000.00,2500.00,2500.00,3000.00,0.00,14000.00,2000.00,90.00,90000.00,76000.00,N,1000
641,354,1.00,6000.00,2000.00,3000.00,2000.00,3000.00,0.00,16000.00,1000.00,80.00,20000.00,4000.00,Y,1000
641,354,1.00,5000.00,2000.00,1500.00,2500.00,3000.00,0.00,14000.00,1500.00,90.00,60000.00,46000.00,N,1000
642,354,0.50,4000.00,2000.00,3000.00,3000.00,2500.00,0.00,14500.00,1600.00,90.00,32000.00,17500.00,Y,1000
642,354,0.50,5000.00,2000.00,1300.00,2500.00,3000.00,0.00,13800.00,1000.00,75.00,38000.00,24200.00,N,1000
643,354,0.50,4000.00,2000.00,3000.00,3000.00,3000.00,0.00,15000.00,1500.00,90.00,30000.00,15000.00,Y,1000
643,354,0.50,5000.00,2000.00,2000.00,2500.00,3500.00,0.00,15000.00,1500.00,90.00,60000.00,45000.00,N,1000
644,354,0.50,3000.00,2500.00,3200.00,2300.00,3000.00,0.00,14000.00,1500.00,70.00,30000.00,16000.00,Y,1000
644,354,0.50,5000.00,2000.00,2000.00,3000.00,3000.00,0.00,15000.00,1500.00,90.00,60000.00,45000.00,N,1000
645,358,1.00,3500.00,4200.00,2500.00,3000.00,3500.00,0.00,16700.00,6500.00,85.00,75000.00,58300.00,Y,1000
645,358,1.00,3000.00,2500.00,2000.00,2000.00,2500.00,0.00,12000.00,4600.00,85.00,115000.00,103000.00,N,1000
646,355,0.50,6000.00,2000.00,5000.00,3500.00,4000.00,0.00,20500.00,1100.00,95.00,121000.00,100500.00,Y,1000
646,355,0.50,0.00,2500.00,5000.00,3000.00,4000.00,0.00,14500.00,7170.00,90.00,186420.00,171920.00,N,1000
717,354,0.50,7000.00,4000.00,13000.00,9000.00,8000.00,3000.00,44000.00,4500.00,90.00,180000.00,136000.00,Y,1000
717,354,0.50,6000.00,5000.00,7000.00,4000.00,4000.00,0.00,26000.00,5000.00,40.00,125000.00,99000.00,N,1000
736,359,1.00,3000.00,1200.00,1800.00,3000.00,3500.00,0.00,12500.00,1250.00,85.00,40000.00,27500.00,Y,1000
736,359,1.00,3500.00,2500.00,3500.00,3000.00,3500.00,0.00,16000.00,1400.00,85.00,49000.00,33000.00,N,1000
737,354,1.00,5000.00,3000.00,2000.00,5000.00,2000.00,0.00,17000.00,2000.00,85.00,60000.00,43000.00,Y,1000
737,354,1.00,3000.00,2000.00,2000.00,3000.00,3500.00,0.00,13500.00,1500.00,90.00,60000.00,46500.00,N,1000
738,229,0.25,3000.00,5000.00,5000.00,4200.00,3500.00,0.00,20700.00,3000.00,90.00,55000.00,34300.00,Y,1000
738,229,0.25,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,N,1000
739,354,0.75,5000.00,4000.00,5000.00,6000.00,5000.00,0.00,25000.00,1000.00,85.00,40000.00,15000.00,Y,1000
739,355,0.75,5000.00,2000.00,12000.00,6000.00,3500.00,4500.00,5000.00,3500.00,75.00,2000.00,-3000.00,Y,1000
739,354,0.75,3000.00,2500.00,2500.00,3000.00,2500.00,0.00,13500.00,2000.00,90.00,80000.00,66500.00,N,1000
739,355,0.75,5000.00,1500.00,7000.00,3000.00,2500.00,0.00,19000.00,1250.00,80.00,45000.00,26000.00,N,1000
740,358,0.75,4000.00,4000.00,3000.00,2500.00,3000.00,0.00,16500.00,5250.00,75.00,58000.00,41500.00,Y,1000
740,358,0.75,3500.00,2500.00,2500.00,3000.00,2000.00,0.00,13500.00,2000.00,85.00,40000.00,26500.00,N,1000
741,355,0.50,3000.00,2000.00,3200.00,4200.00,3500.00,0.00,15900.00,3250.00,75.00,85000.00,69100.00,Y,1000
741,355,0.50,2500.00,2000.00,2000.00,2500.00,2500.00,0.00,11500.00,5000.00,85.00,75000.00,63500.00,N,1000
742,358,0.75,3000.00,5500.00,4000.00,3000.00,1500.00,0.00,17000.00,5000.00,80.00,60000.00,43000.00,Y,1000
742,358,0.75,6000.00,3500.00,4500.00,4000.00,4000.00,0.00,22000.00,5000.00,90.00,90000.00,68000.00,N,1000
743,354,0.50,5000.00,2000.00,2000.00,3000.00,1500.00,0.00,13500.00,1200.00,75.00,26400.00,12900.00,Y,1000
743,354,0.50,5000.00,2000.00,2000.00,3000.00,5000.00,0.00,17000.00,2000.00,90.00,80000.00,63000.00,N,1000
745,354,0.50,5000.00,2000.00,3000.00,2500.00,1800.00,0.00,14300.00,1400.00,80.00,37800.00,23500.00,Y,1000
745,354,0.50,5000.00,2000.00,2000.00,3000.00,5000.00,0.00,17000.00,1500.00,90.00,60000.00,43000.00,N,1000
746,354,0.50,3000.00,2200.00,3200.00,2300.00,3000.00,0.00,13700.00,1800.00,90.00,45000.00,31300.00,Y,1000
746,354,0.50,5000.00,2000.00,2000.00,3000.00,3500.00,0.00,15500.00,1700.00,90.00,68000.00,52500.00,N,1000
765,356,0.75,5000.00,2000.00,2000.00,2000.00,1500.00,0.00,12500.00,2000.00,75.00,24000.00,11500.00,Y,1000
765,356,0.75,3000.00,2000.00,2500.00,2500.00,3000.00,0.00,13000.00,1500.00,80.00,52500.00,39500.00,N,1000
766,354,1.00,6000.00,2000.00,3000.00,2000.00,3000.00,0.00,16000.00,1000.00,80.00,20000.00,4000.00,Y,1000
766,354,1.00,5000.00,2000.00,1500.00,2500.00,3000.00,0.00,14000.00,1500.00,90.00,60000.00,46000.00,N,1000
770,354,0.25,3250.00,3000.00,4450.00,4000.00,2000.00,0.00,16700.00,1000.00,80.00,28000.00,11300.00,Y,1000
770,354,0.25,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,N,1000
771,354,0.35,4000.00,2000.00,10000.00,6000.00,6000.00,0.00,28000.00,6000.00,90.00,90000.00,62000.00,Y,1000
771,354,0.35,5000.00,5000.00,7000.00,4000.00,2000.00,0.00,23000.00,5000.00,80.00,125000.00,102000.00,N,1000
806,354,0.50,6000.00,2000.00,3000.00,2500.00,4000.00,0.00,17500.00,1500.00,85.00,40500.00,23000.00,Y,1000
806,354,0.50,5000.00,2000.00,2500.00,3000.00,4000.00,0.00,16500.00,200.00,75.00,8000.00,-8500.00,N,1000
865,353,0.50,3500.00,4500.00,5000.00,3500.00,2000.00,0.00,18500.00,3500.00,90.00,48000.00,29500.00,Y,1000
865,353,0.50,4000.00,3500.00,3000.00,4000.00,4000.00,0.00,18500.00,3500.00,90.00,140000.00,121500.00,N,1000
866,354,0.50,5000.00,2000.00,2000.00,3000.00,3000.00,0.00,15000.00,1800.00,95.00,45000.00,30000.00,Y,1000
866,354,0.50,6000.00,3000.00,4500.00,5000.00,6000.00,0.00,24500.00,3250.00,90.00,130000.00,105500.00,N,1000
867,354,0.50,3500.00,2200.00,1800.00,2500.00,2000.00,0.00,12000.00,1400.00,80.00,28000.00,16000.00,Y,1000
867,354,0.50,5000.00,3000.00,3000.00,3000.00,3000.00,0.00,17000.00,1400.00,90.00,56000.00,39000.00,N,1000
926,354,0.75,5000.00,4000.00,13000.00,9000.00,8000.00,3000.00,42000.00,4000.00,75.00,160000.00,118000.00,Y,1000
926,354,0.75,5000.00,5000.00,7000.00,4000.00,2000.00,0.00,23000.00,5000.00,85.00,125000.00,102000.00,N,1000
927,354,0.25,4000.00,2800.00,5000.00,4000.00,2000.00,0.00,17800.00,1500.00,75.00,45000.00,27200.00,Y,1000
927,354,0.25,5000.00,5000.00,7000.00,4000.00,2000.00,0.00,23000.00,1250.00,85.00,30000.00,7000.00,N,1000
928,354,0.75,5000.00,3000.00,15000.00,5000.00,5000.00,0.00,33000.00,3000.00,75.00,90000.00,57000.00,Y,1000
928,354,0.75,5000.00,3000.00,15000.00,5000.00,4000.00,0.00,32000.00,3750.00,85.00,67500.00,35500.00,N,1000
929,354,0.75,6000.00,5000.00,12000.00,9000.00,3000.00,0.00,35000.00,5000.00,90.00,250000.00,215000.00,Y,1000
929,354,0.75,6000.00,5000.00,7000.00,4000.00,4000.00,0.00,26000.00,8000.00,80.00,192000.00,166000.00,N,1000
930,351,0.75,4000.00,9000.00,3000.00,7000.00,1000.00,0.00,24000.00,20000.00,80.00,170000.00,146000.00,Y,1000
930,351,0.75,4000.00,9000.00,3000.00,5000.00,1500.00,0.00,22500.00,11000.00,80.00,99000.00,76500.00,N,1000
931,355,0.75,5000.00,3000.00,12000.00,6000.00,10000.00,5000.00,41000.00,7000.00,80.00,70000.00,29000.00,Y,1000
931,355,0.75,4000.00,1800.00,7000.00,2000.00,2000.00,0.00,16800.00,2000.00,80.00,70000.00,53200.00,N,1000
932,354,0.38,8000.00,4000.00,8000.00,8000.00,6000.00,3000.00,37000.00,8000.00,80.00,80000.00,43000.00,Y,1000
932,354,0.38,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,N,1000
935,359,0.75,8000.00,1000.00,2000.00,3000.00,3000.00,0.00,17000.00,1000.00,90.00,60000.00,43000.00,Y,1000
935,359,0.75,3000.00,2000.00,1500.00,2000.00,2000.00,0.00,10500.00,1500.00,90.00,67500.00,57000.00,N,1000
1080,352,0.75,4000.00,9000.00,3000.00,7000.00,1000.00,0.00,24000.00,8000.00,80.00,145000.00,121000.00,Y,1000
1080,352,0.75,5000.00,10000.00,7000.00,5000.00,3000.00,0.00,30000.00,11000.00,80.00,99000.00,69000.00,N,1000

In [3]:
cursor.execute('SELECT * FROM v_act_obs')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'act_obs.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='',encoding='utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [11]:
cursor.execute('SELECT * FROM v_plan_activity_stage')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'plan_acts_dates.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='',encoding='utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [3]:
cursor.execute('SELECT * FROM temp_weather')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'weather.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='',encoding='utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [5]:
cursor.execute('SELECT * FROM v_abnd_acts_name')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'act_abnd.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding= 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [6]:
cursor.execute('SELECT * FROM v_weightage_fo')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'weightage.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding='utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [13]:
cursor.execute("""SELECT temp_farm_crop_baseline.*,t_farm.farm_name, t_user.company_id FROM temp_farm_crop_baseline 
               inner join t_farm on temp_farm_crop_baseline.farm_id = t_farm.farm_id
               inner join t_user on t_farm.user_id = t_user.user_id
               """)

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'baseline_YN.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [9]:
cursor.execute('SELECT * FROM v_cmpl_acts_name')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'act_cmpl.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [10]:
cursor.execute('SELECT * FROM v_activity_status_by_name')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'all_activityplans_byName.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [4]:
cursor.execute('SELECT * FROM v_plans_by_fo')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'plans_by_FO_companies.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [12]:
cursor.execute('SELECT * FROM v_yield_area_data')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'yield_totalArea.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [14]:
cursor.execute('SELECT * FROM v_crop_plan_compliance')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'compliance.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [15]:
cursor.execute('SELECT * FROM v_farm_basic_info')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'farms2.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [16]:
cursor.execute('SELECT * FROM v_plan_wise_acts')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'plan_wise_activities.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)

In [17]:
cursor.execute('SELECT company_id, company_name FROM t_company')

# Fetch column names from cursor description
column_names = [description[0] for description in cursor.description]

# Define the CSV file path
csv_file_path = 'companies.csv'

# Open the CSV file for writing
with open(csv_file_path, 'w', newline='', encoding = 'utf-8') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the column headers
    csv_writer.writerow(column_names)
    
    # Fetch and write each row
    for row in cursor:
        csv_writer.writerow(row)